version: "3.3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=gloat
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    ports:
      - "5432:5432"
  api:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
    links:
      - db
    environment:
      - DATABASE_DNS=db